backend: make sure that exit() exit whole script not just sub-shell

diff --git a/backend/copr-prune-repo b/backend/copr-prune-repo
--- a/backend/copr-prune-repo
+++ b/backend/copr-prune-repo
@@ -8,7 +8,7 @@ if [ ! -d $RESULTDIR ]; then
    exit 1
 fi
 
-pushd $RESULTDIR >/dev/null || ( echo "Could not change to $RESULTDIR"; exit 1)
+pushd $RESULTDIR >/dev/null || { echo "Could not change to $RESULTDIR"; exit 1; }
 
 for REPO in $( ls -d */*/* | grep -v '/repodata$' ); do
     pushd $REPO >/dev/null || continue
