backend: stop if you could not change to directory
which will prevent accidental removal of
/usr/share/ansible/utilities/* (because it contain "fail" file
so if are PWD is in / we can treat is as failed build

diff --git a/backend/copr-prune-repo b/backend/copr-prune-repo
--- a/backend/copr-prune-repo
+++ b/backend/copr-prune-repo
@@ -8,9 +8,10 @@ if [ ! -d $RESULTDIR ]; then
    exit 1
 fi
 
-pushd $RESULTDIR >/dev/null
+pushd $RESULTDIR >/dev/null || ( echo "Could not change to $RESULTDIR"; exit 1)
+
 for REPO in $( ls -d */*/* | grep -v '/repodata$' ); do
-    pushd $REPO >/dev/null
+    pushd $REPO >/dev/null || continue
 
     # Removing failed builds
     for FAILED in $(find -name 'fail' -mtime +$DAYS); do
